export { default as imageLogo } from '../assets/logo1.png'
export { default as imageLogo2 } from '../assets/logo2.png'
export { default as image1 } from '../assets/img1.png'
export { default as image2 } from '../assets/img2.png'
export { default as image3 } from '../assets/img3.png'
